### ISSUE TITLE
Docker is a prerequisite?

### ISSUE THREAD

**Issue by JonathanCrane-DOE** [aws-actions/sustainability-scanner#4]
I created a workflow as a test and I get the error 

```
Build container for action use: '/opt/actions-runner/_work/_actions/aws-actions/sustainability-scanner/v1/Dockerfile'.
  Error: docker: command not found
```
However nowhere in the readme/documentation do I find the word "Docker."  Does docker have to be installed at the system level for this to work?

I'm bascially saying

```yaml

 cf-sustainability-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Sustainability Scanner
        uses: aws-actions/sustainability-scanner@v1
        with: 
          file: <a file>
```
